; Audio constants recovered from Japanese Red Bank 00 and audio-bank symbols.

DEF BIT_BATTLE_OVER_OR_BLACKOUT EQU 5

DEF MUSIC_BIKE_RIDING EQU $D2
DEF MUSIC_SURFING     EQU $D6

DEF AUDIO1_BANK EQU $02
DEF AUDIO2_BANK EQU $08
DEF AUDIO3_BANK EQU $1F

DEF Audio1_UpdateMusicAddr EQU $4000
DEF Audio2_UpdateMusicAddr EQU $455F
DEF Audio3_UpdateMusicAddr EQU $4417

DEF Audio1_PlaySoundAddr EQU $4773
DEF Audio2_PlaySoundAddr EQU $4D1B
DEF Audio3_PlaySoundAddr EQU $4B8A

DEF CHAN5 EQU 4
DEF CHAN6 EQU 5
DEF CHAN7 EQU 6
DEF CHAN8 EQU 7
