; Build selection and ROM0 addresses verified from the supplied source ROMs.
; Define exactly one of:
;   AKA_JP_REV0, AKA_JP_REVA, RED_EN_UE, RED_DE, RED_IT, RED_ES, RED_FR
;
; The current source tree is an incremental Bank 00 reconstruction. These
; constants are intentionally based on bytes verified in the reference ROMs.

IF DEF(AKA_JP_REV0)
	DEF BUILD_JP EQU 1
	DEF VBLANK_VECTOR_TARGET          EQU $0AAC
	DEF TIMER_VECTOR_TARGET           EQU $0D9A
	DEF SERIAL_VECTOR_TARGET          EQU $0BA7
	DEF INIT_TARGET                   EQU $09DA
	DEF DelayFrameAddr                EQU $0B31
	DEF GetRowColAddressBgMapAddr     EQU $0774
	DEF JoypadLowSensitivityAddr      EQU $3879
	DEF PrintLetterDelayAddr          EQU $391D
	DEF Delay3Addr                    EQU $3E07
	DEF ManualTextScrollAddr          EQU $38E1
	DEF DelayFramesAddr               EQU $3781
	DEF PrintBCDNumberAddr            EQU $2FC4
	DEF PrintNumberAddr               EQU $3C8F
	DEF PlaySoundAddr                 EQU $0E45
	DEF WaitForSoundToFinishAddr      EQU $3790
	DEF PlayCryAddr                   EQU $2DC7
	DEF StopAllSoundsAddr             EQU $0A96
	DEF GBPalWhiteOutAddr             EQU $3E15
	DEF HEADER_CART_TYPE              EQU $03
	DEF HEADER_ROM_SIZE               EQU $04
	DEF HEADER_RAM_SIZE               EQU $03
	DEF HEADER_DEST_CODE              EQU $00
	DEF HEADER_VERSION                EQU $00
ENDC

IF DEF(AKA_JP_REVA)
	DEF BUILD_JP EQU 1
	DEF VBLANK_VECTOR_TARGET          EQU $0AAC
	DEF TIMER_VECTOR_TARGET           EQU $0D88
	DEF SERIAL_VECTOR_TARGET          EQU $0BA7
	DEF INIT_TARGET                   EQU $09DA
	DEF DelayFrameAddr                EQU $0B31
	DEF GetRowColAddressBgMapAddr     EQU $0774
	DEF JoypadLowSensitivityAddr      EQU $3867
	DEF PrintLetterDelayAddr          EQU $390B
	DEF Delay3Addr                    EQU $3DF5
	DEF ManualTextScrollAddr          EQU $38CF
	DEF DelayFramesAddr               EQU $376F
	DEF PrintBCDNumberAddr            EQU $2FB2
	DEF PrintNumberAddr               EQU $3C7D
	DEF PlaySoundAddr                 EQU $0E33
	DEF WaitForSoundToFinishAddr      EQU $377E
	DEF PlayCryAddr                   EQU $2DB5
	DEF StopAllSoundsAddr             EQU $0A96
	DEF GBPalWhiteOutAddr             EQU $3E03
	DEF HEADER_CART_TYPE              EQU $03
	DEF HEADER_ROM_SIZE               EQU $04
	DEF HEADER_RAM_SIZE               EQU $03
	DEF HEADER_DEST_CODE              EQU $00
	DEF HEADER_VERSION                EQU $01
ENDC

IF DEF(RED_EN_UE)
	DEF BUILD_WEST EQU 1
	DEF VBLANK_VECTOR_TARGET EQU $2024
	DEF TIMER_VECTOR_TARGET  EQU $2306
	DEF SERIAL_VECTOR_TARGET EQU $2125
	DEF INIT_TARGET          EQU $1F54
	DEF W_ON_CGB             EQU $CF1A
	DEF HEADER_CART_TYPE     EQU $13
	DEF HEADER_ROM_SIZE      EQU $05
	DEF HEADER_RAM_SIZE      EQU $03
	DEF HEADER_DEST_CODE     EQU $01
	DEF HEADER_VERSION       EQU $00
ENDC

IF DEF(RED_DE)
	DEF BUILD_WEST EQU 1
	DEF VBLANK_VECTOR_TARGET EQU $2024
	DEF TIMER_VECTOR_TARGET  EQU $2306
	DEF SERIAL_VECTOR_TARGET EQU $2125
	DEF INIT_TARGET          EQU $1F54
	DEF W_ON_CGB             EQU $CF1F
	DEF HEADER_CART_TYPE     EQU $1B
	DEF HEADER_ROM_SIZE      EQU $05
	DEF HEADER_RAM_SIZE      EQU $03
	DEF HEADER_DEST_CODE     EQU $01
	DEF HEADER_VERSION       EQU $00
ENDC

IF DEF(RED_IT)
	DEF BUILD_WEST EQU 1
	DEF VBLANK_VECTOR_TARGET EQU $2024
	DEF TIMER_VECTOR_TARGET  EQU $2306
	DEF SERIAL_VECTOR_TARGET EQU $2125
	DEF INIT_TARGET          EQU $1F54
	DEF W_ON_CGB             EQU $CF1F
	DEF HEADER_CART_TYPE     EQU $1B
	DEF HEADER_ROM_SIZE      EQU $05
	DEF HEADER_RAM_SIZE      EQU $03
	DEF HEADER_DEST_CODE     EQU $01
	DEF HEADER_VERSION       EQU $00
ENDC

IF DEF(RED_ES)
	DEF BUILD_WEST EQU 1
	DEF VBLANK_VECTOR_TARGET EQU $2023
	DEF TIMER_VECTOR_TARGET  EQU $2305
	DEF SERIAL_VECTOR_TARGET EQU $2124
	DEF INIT_TARGET          EQU $1F53
	DEF W_ON_CGB             EQU $CF1F
	DEF HEADER_CART_TYPE     EQU $1B
	DEF HEADER_ROM_SIZE      EQU $05
	DEF HEADER_RAM_SIZE      EQU $03
	DEF HEADER_DEST_CODE     EQU $01
	DEF HEADER_VERSION       EQU $00
ENDC

IF DEF(RED_FR)
	DEF BUILD_WEST EQU 1
	DEF VBLANK_VECTOR_TARGET EQU $2020
	DEF TIMER_VECTOR_TARGET  EQU $2302
	DEF SERIAL_VECTOR_TARGET EQU $2121
	DEF INIT_TARGET          EQU $1F50
	DEF W_ON_CGB             EQU $CF1F
	DEF HEADER_CART_TYPE     EQU $1B
	DEF HEADER_ROM_SIZE      EQU $05
	DEF HEADER_RAM_SIZE      EQU $03
	DEF HEADER_DEST_CODE     EQU $01
	DEF HEADER_VERSION       EQU $00
ENDC
