; Game Boy hardware addresses used by the reconstructed ROM0 routines.

DEF rSB   EQU $FF01
DEF rSC   EQU $FF02
DEF rDIV  EQU $FF04
DEF rTMA  EQU $FF06
DEF rTAC  EQU $FF07
DEF rIF   EQU $FF0F
DEF rLCDC EQU $FF40
DEF rSTAT EQU $FF41
DEF rSCY  EQU $FF42
DEF rSCX  EQU $FF43
DEF rLY   EQU $FF44
DEF rBGP  EQU $FF47
DEF rOBP0 EQU $FF48
DEF rOBP1 EQU $FF49
DEF rWY   EQU $FF4A
DEF rWX   EQU $FF4B
DEF rIE   EQU $FFFF
DEF rROMB EQU $2000

; Serial-control bits.
DEF SC_EXTERNAL EQU $00
DEF SC_INTERNAL EQU $01
DEF SC_START    EQU $80

; Interrupt-enable bits.
DEF IE_VBLANK EQU $01
DEF IE_STAT   EQU $02
DEF IE_TIMER  EQU $04
DEF IE_SERIAL EQU $08
