; Serial/link constants recovered from Japanese Red Bank 00.

DEF ESTABLISH_CONNECTION_WITH_EXTERNAL_CLOCK EQU $02

DEF USING_EXTERNAL_CLOCK       EQU $01
DEF USING_INTERNAL_CLOCK       EQU $02
DEF CONNECTION_NOT_ESTABLISHED EQU $FF

DEF SERIAL_PREAMBLE_BYTE EQU $FD
DEF SERIAL_NO_DATA_BYTE  EQU $FE

DEF LINK_STATE_RESET EQU $05 ; unused reset-link state checked only by Rev 0

DEF PrintWaitingTextBank EQU $01
DEF PrintWaitingTextAddr EQU $49ED
